# fly.toml file generated for evelyn on 2023-06-25T19:53:25+02:00

app = "evelyn"
primary_region = "cdg"

[http_service]
  internal_port = 80
  force_https = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
